// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/announce/announce_page.dart' as a0;
import 'app/app_page.dart' as a1;
import 'app/favorites/favorites_page.dart' as a2;
import 'app/home/home_page.dart' as a3;
import 'app/profile/profile_page.dart' as a4;
import 'app/search/search_page.dart' as a5;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/announce',
        uri: Uri.parse('/announce'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.AnnouncePage(),
        ),
      ),
      RouteEntity(
        key: '/',
        uri: Uri.parse('/'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.AppPage(),
        ),
      ),
      RouteEntity(
        key: '/favorites',
        uri: Uri.parse('/favorites'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.FavoritesPage(),
        ),
      ),
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a3.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/profile',
        uri: Uri.parse('/profile'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a4.ProfilePage(),
        ),
      ),
      RouteEntity(
        key: '/search',
        uri: Uri.parse('/search'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a5.SearchPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  announce: '/announce',
  favorites: '/favorites',
  home: '/home',
  profile: '/profile',
  search: '/search',
);
